# Setup
title:               DEV ℧
tagline:             'Developer Diary'
description:         '주니어 백엔드 개발자'
url:                 https://dh37789.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
github:              https://github.com/dh37789
future:              true
published:           true

# About/contact
author:
  name:              Oh MyeongHak
  email:             dhaudgkr@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-B4JZGH42KG

category_dir: category/

permalink: /:categories/:title/
