# Setup
title:               DEV ℧
tagline:             'Developer Diary'
description:         '주니어 백엔드 개발자'
url:                 https://dh37789.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Oh MyeongHak
  email:             dhaudgkr@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

category_dir: category/
