# 메뉴구성도
menu:
  홈: /
  기록: /archives
  카테고리: /categories
  태그: /tags

# https://github.com/mattboldt/typed.js
subtitle:
  enable: true # 효과 활성화 여부
  text: 안녕하세요 # 표시된 텍스트
  text2: 저의 블로그에 오신걸 # 재생하려면 스크롤하세요. 필요하지 않은 경우 비워둘 수 있습니다.
  text3: 환영합니다. # 최대 세 단락의 텍스트가 지원됩니다.
  startDelay: 0 # 지연 딜레이
  typeSpeed: 200 # 타이핑 속도
  loop: true # 순환 여부
  backSpeed: 100 # 롤백 속도
  showCursor: true # 커서 표시 여부

# favicon and sidebar
favicon: /favicon.ico
logo: /images/ayer-side.svg

# 커버 구성
# enable-덮개 활성화 여부；path-커버 배경 이미지；logo-커버 logo
cover:
  enable: true
  path: /images/cover3.jpg
  logo: false #/images/ayer.svg

# 페이지 상단의 진행률 표시줄
progressBar: true

# 게시판 모듈
broadcast:
  enable: true # true，false
  type: 1
  text: 즐거운 하루 되세용 ㅎㅎ

# 기사 구성
# 기사가 너무 깁니다，
  #버튼 텍스트를 자릅니다(잘라야 하는 줄에 이 태그를 추가합니다: <!--more-->).
excerpt_link: 더 읽어보기...
# 각 기사에 수동으로 더 많은 태그를 추가하는 것이 번거롭다고 생각하고 홈페이지에 전체 텍스트를 표시하고 싶지 않다면 excerpt_all을 true로 설정하여 기사 아카이브만 홈페이지에 표시되도록 할 수 있습니다.
excerpt_all: false

# 코드 복사 버튼 활성화 여부
copy_btn: true
# 기사 공유 버튼 활성화 여부
share_enable: true
# 기사 공유 텍스트
share_text: share

# 페이지 관련 문구
nav_text:
  page_prev: 이전 페이지
  page_next: 다음 페이지
  post_prev: 이전으로
  post_next: 다음으로

# 기사 페이지에 목차 표시 여부
toc: true

# 기사의 사진이 확대하려면 클릭을 지원합니까?
image_viewer: true

# https://github.com/willin/hexo-wordcount
# 단어 수 활성화 여부(비활성화하려면 활성화를 false로 설정하십시오)
# md 파일의 Front-matter에서 `no_word_count: true` 속성을 개별적으로 설정하여 단어 수를 사용자 지정하고 닫을 수도 있습니다.
word_count:
  enable: true
  # 기사 상세정보에만 표시됨(홈페이지에는 표시되지 않음)
  only_article_visit: true

# 리워드 요구
# 보상 유형 설정: 0-보상 끄기, 1-reward:기사에 해당하는 md 파일의 true 속성, 그러면 보상 있음, 2-모든 기사에 보상 있음
reward_type: 0
# 보상 wording
reward_wording: "커피한잔 사주세요~"

# 저작권 고지
# 저작권 표시 유형 설정: 0 - 저작권 표시 닫기, 1 - 기사에 해당하는 md 파일에 저작권 있음: true 속성, 그리고 저작권 표시 있음, 2 - 모든 기사에 저작권 표시 있음
copyright_type: 2

# 검색 활성화 여부
# 설치해야함 hexo-generator-searchdb(https://github.com/theme-next/hexo-generator-searchdb)
search: true

# RSS 피드(먼저 hexo-generator-feed 플러그인을 설치한 다음 블로그 루트 디렉토리 config로 이동하여 구성합니다.)
# 표시를 원하지 않으시면 비워두시면 됩니다
rss:

# 다크 모드 스위치 활성화 여부
darkmode: true

# 동적 배경 효과: 0-off, 1-동적 라인(마우스를 따라감)
canvas_bg: 0

# Customize the mouse style, directly replace the /images/mouse.cur file
mouse:
  enable: false
  path: /images/mouse.cur

# 마우스 클릭 효과: 0-off, 1-하트, 2-폭발 폭죽, 3입자 폭죽
click_effect: 1

# 페이지 너비 사용자 지정(수정하지 않는 것이 좋습니다. 레이아웃 혼동이 발생할 수 있음), article_width 기사 너비, sidebar_width 사이드바 너비
layout:
  article_width: 80rem
  sidebar_width: 8rem

# GitHub Ribbons - 표지의 오른쪽 상단 모서리에 있는 포크, 스타일 변경 및 소스/이미지 디렉토리의 포크 이미지를 직접 교체
github:
  enable: true
  url: https://github.com/dh37789


## 访问量统计(不蒜子)
#busuanzi:
#  enable: true
#
## 友盟cnzz统计(url填js代码src链接)
#cnzz:
#  enable: true
#  url: https://s9.cnzz.com/z_stat.php?id=1278069914&web_id=1278069914

# Google Analytics
google_analytics: ""

# Mathjax 수학 공식
mathjax: false

# Katex수학공식(allpost가 false로 설정되면 head에 math, true가 포함된 기사만 열립니다.)
# hexo 렌더러를 교체해야 합니다. npm un hexo-renderer-marked -S && npm i hexo-renderer-markdown-it-katex -S
katex:
  enable: false # true
  allpost: true
  copy_tex: false

# mermaid순서도(https://mermaid-js.github.io/mermaid/)
mermaid:
  enable: false
  cdn: https://cdn.staticfile.org/mermaid/8.14.0/mermaid.min.js
  theme: forest

# since
since: 2022

## 연결
#friends_link:
#  Ayer主题: #网站名称
#    #网站地址
#    url: https://github.com/Shen-Yu/hexo-theme-ayer
#    #网站图片(可忽略不写)
#    img: /images/ayer.png
#  GitHub:
#    url: https://github.com/Shen-Yu
#    img: /images/github.png
#  码云:
#    url: https://gitee.com/shen-yu
#    img: /images/gitee.png
#  Hexo官网:
#    url: https://hexo.io
#    img: /images/hexo.png
#  Hexo图表插件:
#    url: https://github.com/Shen-Yu/hexo-tag-chart
#    img: /images/hexo-tag-chart.png

# 댓글
# Gitalk(https://github.com/gitalk/gitalk)
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# 홈페이지 광고 구성
#ads:
#  ad_1:
#    title:
#    img:
#    url:
#    width:
#  ad_2:
#    title:
#    img:
#    url:
#    width:

# 웹 사이트에 대한 암호화된 액세스，비밀번호는 임의의 문자로 설정 가능
lock:
  enable: false
  password: 123456
